---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install
    apt:
      name: apache2
      state: latest

  - name: Add PHP support for apache
    apt:
      name: libapache2-mod-php
      state: latest
