---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: Remove apache
    apt:
      name: apache2
      state: absent

  - name: Remove PHP support for apache
    apt:
      name: libapache2-mod-php
      state: absent
