---
-  hosts: all
   become: true
   pre_tasks:

  - name: install updates (CentOS)
    tags: always                    # this will always run
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"  

  - name: install updates (Ubuntu)
    tags: always                    # this will always run
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 

# do all the installing only against the webservers

-  hosts: web_servers
   become: true
   tasks: 	# tasks could be replaced by pre_tasks whose job is to make sure this task runs first before anything else

  - name: install apache2 and php packages for Ubuntu
    tags: apache, apache2,ubuntu
    apt:
      name: 
	- apache2			
	- libapache2-mod-php
	  state: latest
    when: ansible_distribution == "Ubuntu"    

  - name: install apache2, php packages for CentOS
    tags: apache, centos,httpd
    dnf:
      name: 
        - httpd  			
        - php          
    when: ansible_distribution == "CentOS" 

-  hosts: db_servers
   become: true
   tasks: 	

  - name: install mariadb package (CentOS)
    tags: centos,db, maridb
    dnf:
      name: mariadb			
      state: latest
    when: ansible_distribution == "CentOS" 

  - name: install mariadb package (Ubuntu)
    tags: db, mariadb,ubuntu
    apt:
      name: mariadb-server			
      state: latest
    when: ansible_distribution == "Ubuntu" 

-  hosts: file_servers
   become: true
   tasks: 	

  - name: install samba package 
    tags: samba
    package:   # not different for CenOS and Ubuntu
      name: Samba			
      state: latest

